---
# tasks file for ansible-role-pkg-update

# Setup/upgrade tasks.

- name: Upgrade package on RedHat.
  include_tasks: upgrade-RedHat.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- name: Set up Ansible on Ubuntu.
  include_tasks: upgrade-Ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_install_method == 'package'