---
# tasks file for ansible-role-pkg-update

# Upgrade tasks.
- name: Upgrade and reboot RedHat disto.
  include_tasks: upgrade-RedHat.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- name: Upgrade and reboot Ubuntu distro.
  include_tasks: upgrade-Ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"